ARG TARGETOS TARGETARCH

FROM
FROM scratch
# introduce a parsing error on purpose
FROM scratch AS 

FROM scratch AS base
FROM scratch AS tests
FROM scratch AS release

# this ENV line validates the FROM argument parsing
ENV a=b c=d e=f

ARG argOne
ARG argTwo

ARG argOnePredefined=v1
