name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - v*
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
